// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface BaseRelayRecipient$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "BaseRelayRecipient";
  readonly sourceName: "contracts/BaseRelayRecipient.sol";
  readonly abi: [];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/BaseRelayRecipient.sol";
  readonly buildInfoId: "solc-0_8_24-a425868d7c79aee58a7f36e0d98164b683129134";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["BaseRelayRecipient"]: BaseRelayRecipient$Type;
    ["contracts/BaseRelayRecipient.sol:BaseRelayRecipient"]: BaseRelayRecipient$Type;
  }
}